export const BAZAR_CATEGORIES = [
  { en: "Vegetables", bn: "সবজি" },
  { en: "Protein", bn: "প্রোটিন" },
  { en: "Grocery", bn: "মুদি" },
  { en: "Crockery", bn: "ক্রোকারিজ" },
  { en: "Fruit", bn: "ফলসমূহ" },
  { en: "Utilities", bn: "ইউটিলিটি ও বিল" },
  { en: "Others", bn: "অন্যান্য" }
];

export const PRELOADED_BAZAR_ITEMS = [
  // Vegetables
  { name: "Potato", bn: "আলু", category: "Vegetables", unit: "kg" },
  { name: "Onion", bn: "পেঁয়াজ", category: "Vegetables", unit: "kg" },
  { name: "Tomato", bn: "টমেটো", category: "Vegetables", unit: "kg" },
  { name: "Green Chili", bn: "কাঁচা মরিচ", category: "Vegetables", unit: "kg" },
  { name: "Brinjal", bn: "বেগুন", category: "Vegetables", unit: "kg" },
  { name: "Garlic", bn: "রসুন", category: "Vegetables", unit: "kg" },
  { name: "Ginger", bn: "আদা", category: "Vegetables", unit: "kg" },
  { name: "Cucumber", bn: "শশা", category: "Vegetables", unit: "kg" },
  { name: "Pumpkin", bn: "মিষ্টি কুমড়া", category: "Vegetables", unit: "piece" },
  { name: "Spinach", bn: "পালং শাক", category: "Vegetables", unit: "bundle" },
  { name: "Cabbage", bn: "বাঁধাকপি", category: "Vegetables", unit: "piece" },
  { name: "Cauliflower", bn: "ফুলকপি", category: "Vegetables", unit: "piece" },
  { name: "Lady Finger", bn: "ঢেঁড়স", category: "Vegetables", unit: "kg" },
  { name: "Bitter Gourd", bn: "করলা", category: "Vegetables", unit: "kg" },
  { name: "Bottle Gourd", bn: "লাউ", category: "Vegetables", unit: "piece" },
  { name: "Radish", bn: "মুলা", category: "Vegetables", unit: "kg" },
  { name: "Pointed Gourd", bn: "পটল", category: "Vegetables", unit: "kg" },
  { name: "Papaya", bn: "পেঁপে", category: "Vegetables", unit: "kg" },
  { name: "Lemon", bn: "লেবু", category: "Vegetables", unit: "piece" },
  { name: "Coriander Leaves", bn: "ধনে পাতা", category: "Vegetables", unit: "bundle" },
  { name: "Snake Gourd", bn: "চিচিঙ্গা", category: "Vegetables", unit: "kg" },
  { name: "Ridge Gourd", bn: "ঝিঙা", category: "Vegetables", unit: "kg" },
  { name: "Sponge Gourd", bn: "ধুন্দুল", category: "Vegetables", unit: "kg" },
  { name: "Spiny Gourd", bn: "কাঁকরোল", category: "Vegetables", unit: "kg" },
  { name: "Taro Root", bn: "কচু", category: "Vegetables", unit: "kg" },
  { name: "Taro Loti", bn: "কচুর লতি", category: "Vegetables", unit: "kg" },
  { name: "Drumstick", bn: "সজনে ডাঁটা", category: "Vegetables", unit: "kg" },
  { name: "Red Spinach", bn: "লাল শাক", category: "Vegetables", unit: "bundle" },
  { name: "Water Spinach", bn: "কলমি শাক", category: "Vegetables", unit: "bundle" },
  { name: "Malabar Spinach", bn: "পুঁই শাক", category: "Vegetables", unit: "bundle" },
  { name: "Green Banana", bn: "কাঁচা কলা", category: "Vegetables", unit: "piece" },
  { name: "Sweet Potato", bn: "মিষ্টি আলু", category: "Vegetables", unit: "kg" },
  { name: "Beans", bn: "শিম", category: "Vegetables", unit: "kg" },
  { name: "Peas", bn: "মটরশুঁটি", category: "Vegetables", unit: "kg" },
  { name: "Green Papaya", bn: "কাঁচা পেঁপে", category: "Vegetables", unit: "kg" },
  { name: "Ash Gourd", bn: "চাল কুমড়া", category: "Vegetables", unit: "piece" },
  { name: "Teasel Gourd", bn: "কাঁকরোল", category: "Vegetables", unit: "kg" },
  { name: "Elephant Foot Yam", bn: "ওল কচু", category: "Vegetables", unit: "kg" },
  { name: "Mint Leaves", bn: "পুদিনা পাতা", category: "Vegetables", unit: "bundle" },
  { name: "Taro Stems", bn: "কচুর ডগা", category: "Vegetables", unit: "bundle" },
  { name: "Stem Amaranth", bn: "ডাটা শাক", category: "Vegetables", unit: "bundle" },

  // Protein
  { name: "Beef", bn: "গরুর মাংস", category: "Protein", unit: "kg" },
  { name: "Mutton", bn: "খাসির মাংস", category: "Protein", unit: "kg" },
  { name: "Chicken", bn: "মুরগির মাংস", category: "Protein", unit: "kg" },
  { name: "Desi Chicken", bn: "দেশি মুরগি", category: "Protein", unit: "piece" },
  { name: "Duck", bn: "হাঁস", category: "Protein", unit: "piece" },
  { name: "Hilsa", bn: "ইলিশ মাছ", category: "Protein", unit: "piece" },
  { name: "Rohu", bn: "রুই মাছ", category: "Protein", unit: "kg" },
  { name: "Katla", bn: "কাতলা মাছ", category: "Protein", unit: "kg" },
  { name: "Pangas", bn: "পাঙ্গাস মাছ", category: "Protein", unit: "kg" },
  { name: "Tilapia", bn: "তেলাপিয়া মাছ", category: "Protein", unit: "kg" },
  { name: "Koi Fish", bn: "কৈ মাছ", category: "Protein", unit: "kg" },
  { name: "Magur Fish", bn: "মাগুর মাছ", category: "Protein", unit: "kg" },
  { name: "Singi Fish", bn: "শিং মাছ", category: "Protein", unit: "kg" },
  { name: "Pabda Fish", bn: "পাবদা মাছ", category: "Protein", unit: "kg" },
  { name: "Tengra Fish", bn: "ট্যাংরা মাছ", category: "Protein", unit: "kg" },
  { name: "Boal Fish", bn: "বোয়াল মাছ", category: "Protein", unit: "kg" },
  { name: "Chitol Fish", bn: "চিতল মাছ", category: "Protein", unit: "kg" },
  { name: "Kachki Fish", bn: "কাচকি মাছ", category: "Protein", unit: "kg" },
  { name: "Mola Fish", bn: "মলা মাছ", category: "Protein", unit: "kg" },
  { name: "Bele Fish", bn: "বেলে মাছ", category: "Protein", unit: "kg" },
  { name: "Shol Fish", bn: "শোল মাছ", category: "Protein", unit: "kg" },
  { name: "Taki Fish", bn: "টাকি মাছ", category: "Protein", unit: "kg" },
  { name: "Rupchanda", bn: "রূপচাঁদা মাছ", category: "Protein", unit: "kg" },
  { name: "Shrimp (Small)", bn: "ছোট চিংড়ি", category: "Protein", unit: "kg" },
  { name: "Shrimp (Medium)", bn: "মাঝারি চিংড়ি", category: "Protein", unit: "kg" },
  { name: "Lobster", bn: "গলদা চিংড়ি", category: "Protein", unit: "kg" },
  { name: "Crab", bn: "কাঁকড়া", category: "Protein", unit: "kg" },
  { name: "Eggs (Chicken)", bn: "মুরগির ডিম", category: "Protein", unit: "dozen" },
  { name: "Eggs (Duck)", bn: "হাঁসের ডিম", category: "Protein", unit: "dozen" },

  // Grocery
  { name: "Rice (Miniket)", bn: "মিনিকেট চাল", category: "Grocery", unit: "kg" },
  { name: "Rice (Nazirshail)", bn: "নাজিরশাইল চাল", category: "Grocery", unit: "kg" },
  { name: "Rice (Pulao)", bn: "পোলাও চাল", category: "Grocery", unit: "kg" },
  { name: "Oil (Soybean)", bn: "সয়াবিন তেল", category: "Grocery", unit: "litre" },
  { name: "Mustard Oil", bn: "সরিষার তেল", category: "Grocery", unit: "litre" },
  { name: "Salt", bn: "লবণ", category: "Grocery", unit: "kg" },
  { name: "Sugar", bn: "চিনি", category: "Grocery", unit: "kg" },
  { name: "Brown Sugar", bn: "লাল চিনি", category: "Grocery", unit: "kg" },
  { name: "Lentils (Musur)", bn: "মসুর ডাল", category: "Grocery", unit: "kg" },
  { name: "Lentils (Moong)", bn: "মুগ ডাল", category: "Grocery", unit: "kg" },
  { name: "Lentils (Boot)", bn: "বুট ডাল", category: "Grocery", unit: "kg" },
  { name: "Flour (Atta)", bn: "আটা", category: "Grocery", unit: "kg" },
  { name: "Flour (Maida)", bn: "ময়দা", category: "Grocery", unit: "kg" },
  { name: "Semolina (Suji)", bn: "সুজি", category: "Grocery", unit: "packet" },
  { name: "Milk (Powder)", bn: "গুড়া দুধ", category: "Grocery", unit: "packet" },
  { name: "Milk (Liquid)", bn: "তরল দুধ", category: "Grocery", unit: "litre" },
  { name: "Tea Leaves", bn: "চা পাতা", category: "Grocery", unit: "packet" },
  { name: "Turmeric Powder", bn: "হলুদ গুঁড়া", category: "Grocery", unit: "packet" },
  { name: "Chili Powder", bn: "মরিচ গুঁড়া", category: "Grocery", unit: "packet" },
  { name: "Cumin Powder", bn: "জিরা গুঁড়া", category: "Grocery", unit: "packet" },
  { name: "Coriander Powder", bn: "ধনিয়া গুঁড়া", category: "Grocery", unit: "packet" },
  { name: "Cardamom", bn: "এলাচ", category: "Grocery", unit: "gram" },
  { name: "Cinnamon", bn: "দারুচিনি", category: "Grocery", unit: "gram" },
  { name: "Cloves", bn: "লবঙ্গ", category: "Grocery", unit: "gram" },
  { name: "Bay Leaf", bn: "তেজপাতা", category: "Grocery", unit: "gram" },
  { name: "Black Pepper", bn: "গোল মরিচ", category: "Grocery", unit: "gram" },
  { name: "Soap (Body)", bn: "গায়ের সাবান", category: "Grocery", unit: "piece" },
  { name: "Soap (Laundry)", bn: "কাপড়ের সাবান", category: "Grocery", unit: "piece" },
  { name: "Detergent", bn: "ডিটারজেন্ট", category: "Grocery", unit: "kg" },
  { name: "Dish Wash", bn: "ডিশ ওয়াশ", category: "Grocery", unit: "piece" },
  { name: "Shampoo", bn: "শ্যাম্পু", category: "Grocery", unit: "bottle" },
  { name: "Toothpaste", bn: "টুথপেস্ট", category: "Grocery", unit: "piece" },
  { name: "Tissue Paper", bn: "টিস্যু পেপার", category: "Grocery", unit: "packet" },
  { name: "Matches", bn: "দিয়াশলাই", category: "Grocery", unit: "box" },

  // Utilities & Bills
  { name: "House Rent", bn: "বাসা ভাড়া", category: "Utilities", unit: "month" },
  { name: "Internet Bill", bn: "ইন্টারনেট বিল", category: "Utilities", unit: "month" },
  { name: "Mobile Recharge", bn: "মোবাইল রিচার্জ", category: "Utilities", unit: "taka" },
  { name: "Electricity Bill", bn: "বিদ্যুৎ বিল", category: "Utilities", unit: "month" },
  { name: "Water Bill", bn: "পানির বিল", category: "Utilities", unit: "month" },
  { name: "Gas Bill", bn: "গ্যাস বিল", category: "Utilities", unit: "month" },
  { name: "Garbage Bill", bn: "ময়লার বিল", category: "Utilities", unit: "month" },
  { name: "Maid Salary", bn: "কাজের বুয়ার বিল", category: "Utilities", unit: "month" },
  { name: "Service Charge", bn: "সার্ভিস চার্জ", category: "Utilities", unit: "month" },
  { name: "Dish Bill", bn: "ডিশ বিল", category: "Utilities", unit: "month" },

  // Crockery & Kitchenware
  { name: "Plate (Melamine)", bn: "মেলামাইন প্লেট", category: "Crockery", unit: "piece" },
  { name: "Plate (Ceramic)", bn: "সিরামিক প্লেট", category: "Crockery", unit: "piece" },
  { name: "Glass (Steel)", bn: "স্টিল গ্লাস", category: "Crockery", unit: "piece" },
  { name: "Glass (Glass)", bn: "কাঁচের গ্লাস", category: "Crockery", unit: "piece" },
  { name: "Bowl (Large)", bn: "বড় বাটি", category: "Crockery", unit: "piece" },
  { name: "Bowl (Small)", bn: "ছোট বাটি", category: "Crockery", unit: "piece" },
  { name: "Spoon (Rice)", bn: "ভাতের চামচ", category: "Crockery", unit: "piece" },
  { name: "Spoon (Tea)", bn: "চা চামচ", category: "Crockery", unit: "piece" },
  { name: "Fork", bn: "কাঁটা চামচ", category: "Crockery", unit: "piece" },
  { name: "Knife (Kitchen)", bn: "রান্নাঘরের ছুরি", category: "Crockery", unit: "piece" },
  { name: "Pan (Fry)", bn: "ফ্রাই প্যান", category: "Crockery", unit: "piece" },
  { name: "Pan (Cooking)", bn: "কড়াই", category: "Crockery", unit: "piece" },
  { name: "Pressure Cooker", bn: "প্রেশার কুকার", category: "Crockery", unit: "piece" },
  { name: "Kettle", bn: "কেটলি", category: "Crockery", unit: "piece" },
  { name: "Jug (Water)", bn: "পানির জগ", category: "Crockery", unit: "piece" },
  { name: "Mug", bn: "মগ", category: "Crockery", unit: "piece" },
  { name: "Cup & Saucer", bn: "কাপ পিরিচ", category: "Crockery", unit: "set" },
  { name: "Tray", bn: "ট্রে", category: "Crockery", unit: "piece" },
  { name: "Chopping Board", bn: "কাটিং বোর্ড", category: "Crockery", unit: "piece" },
  { name: "Spatula", bn: "খুন্তি", category: "Crockery", unit: "piece" },
  { name: "Grater", bn: "কুড়ানি", category: "Crockery", unit: "piece" },
  { name: "Peeler", bn: "পিলার", category: "Crockery", unit: "piece" },
  { name: "Whisk", bn: "হ্যান্ড হুইস্ক", category: "Crockery", unit: "piece" },
  { name: "Strainer", bn: "ছাঁকনি", category: "Crockery", unit: "piece" },
  { name: "Tongs", bn: "চিমটা", category: "Crockery", unit: "piece" },
  { name: "Rice Cooker", bn: "রাইস কুকার", category: "Crockery", unit: "piece" },
  { name: "Blender", bn: "ব্লেন্ডার", category: "Crockery", unit: "piece" },
  { name: "Electric Kettle", bn: "ইলেকট্রিক কেটলি", category: "Crockery", unit: "piece" },
  { name: "Lunch Box", bn: "লাঞ্চ বক্স", category: "Crockery", unit: "piece" },
  { name: "Water Bottle", bn: "পানির বোতল", category: "Crockery", unit: "piece" },
  { name: "Hot Pot", bn: "হট পট", category: "Crockery", unit: "piece" },
  { name: "Dinner Set", bn: "ডিনার সেট", category: "Crockery", unit: "set" },
  { name: "Steel Bowl", bn: "স্টিল বাটি", category: "Crockery", unit: "piece" },
  { name: "Non-stick Pan", bn: "নন-স্টিক কড়াই", category: "Crockery", unit: "piece" },
  { name: "Saucepen", bn: "সসপ্যান", category: "Crockery", unit: "piece" },
  { name: "Bucket", bn: "বালতি", category: "Crockery", unit: "piece" },
  { name: "Boti", bn: "বটি", category: "Crockery", unit: "piece" },

  // Fruits
  { name: "Apple", bn: "আপেল", category: "Fruit", unit: "kg" },
  { name: "Banana (Sagor)", bn: "সাগর কলা", category: "Fruit", unit: "dozen" },
  { name: "Banana (Champa)", bn: "চাঁপা কলা", category: "Fruit", unit: "dozen" },
  { name: "Mango (Fazli)", bn: "ফজলি আম", category: "Fruit", unit: "kg" },
  { name: "Mango (Langra)", bn: "ল্যাংড়া আম", category: "Fruit", unit: "kg" },
  { name: "Mango (Himsagar)", bn: "হিমসাগর আম", category: "Fruit", unit: "kg" },
  { name: "Jackfruit", bn: "কাঁঠাল", category: "Fruit", unit: "piece" },
  { name: "Litchi", bn: "লিচু", category: "Fruit", unit: "100 pcs" },
  { name: "Pineapple", bn: "আনারস", category: "Fruit", unit: "piece" },
  { name: "Watermelon", bn: "তরমুজ", category: "Fruit", unit: "piece" },
  { name: "Guava", bn: "পেয়ারা", category: "Fruit", unit: "kg" },
  { name: "Papaya (Ripe)", bn: "পাকা পেঁপে", category: "Fruit", unit: "kg" },
  { name: "Pomegranate", bn: "ডালিম/আনার", category: "Fruit", unit: "kg" },
  { name: "Grapes (Green)", bn: "সবুজ আঙ্গুর", category: "Fruit", unit: "kg" },
  { name: "Grapes (Black)", bn: "কালো আঙ্গুর", category: "Fruit", unit: "kg" },
  { name: "Orange", bn: "কমলা", category: "Fruit", unit: "kg" },
  { name: "Malta", bn: "মাল্টা", category: "Fruit", unit: "kg" },
  { name: "Pear", bn: "নাশপাতি", category: "Fruit", unit: "kg" },
  { name: "Plum", bn: "বরই", category: "Fruit", unit: "kg" },
  { name: "Dragon Fruit", bn: "ড্রাগন ফল", category: "Fruit", unit: "kg" },
  { name: "Wood Apple", bn: "বেল", category: "Fruit", unit: "piece" },
  { name: "Hog Plum", bn: "আমড়া", category: "Fruit", unit: "kg" },
  { name: "Star Fruit", bn: "কামরাঙা", category: "Fruit", unit: "kg" },
  { name: "Jujube", bn: "কুল/বরই", category: "Fruit", unit: "kg" },
  { name: "Dates", bn: "খেজুর", category: "Fruit", unit: "box" },
  { name: "Coconut", bn: "নারকেল", category: "Fruit", unit: "piece" },
  { name: "Green Coconut", bn: "ডাব", category: "Fruit", unit: "piece" },

  // Others
  { name: "Candle", bn: "মোমবাতি", category: "Others", unit: "box" },
  { name: "Coil", bn: "কয়েল", category: "Others", unit: "packet" },
  { name: "Bulb", bn: "বাল্ব", category: "Others", unit: "piece" },
  { name: "Battery", bn: "ব্যাটারি", category: "Others", unit: "piece" },
  { name: "Broom", bn: "ঝাড়ু", category: "Others", unit: "piece" },
  { name: "Mop", bn: "মপ", category: "Others", unit: "piece" }
];

export const BILL_CATEGORIES = [
  { en: "House Rent", bn: "বাসা ভাড়া" },
  { en: "Electricity", bn: "বিদ্যুৎ বিল" },
  { en: "Gas", bn: "গ্যাস বিল" },
  { en: "Water", bn: "পানির বিল" },
  { en: "Internet", bn: "ইন্টারনেট বিল" },
  { en: "Mobile Recharge", bn: "মোবাইল রিচার্জ" },
  { en: "Garbage Bill", bn: "ময়লার বিল" },
  { en: "Maid Salary", bn: "কাজের বুয়ার বিল" },
  { en: "Direct TV/Dish", bn: "ডিশ বিল" },
  { en: "Service Charge", bn: "সার্ভিস চার্জ" }
];

export const EDUCATION_SUB_CATEGORIES = [
  { en: "Monthly Tuition Fee", bn: "মাসিক বেতন" },
  { en: "Exam Fee", bn: "পরীক্ষার ফি" },
  { en: "Stationery", bn: "স্টেশনারি" },
  { en: "Uniform", bn: "ইউনিফর্ম" },
  { en: "School Transport", bn: "স্কুল পরিবহন" },
  { en: "Tutor Fee", bn: "গৃহশিক্ষকের ফি" },
  { en: "Books", bn: "বইপত্র" }
];

export const INCOME_SOURCES = [
  { en: "Salary", bn: "বেতন" },
  { en: "Bonus", bn: "বোনাস" },
  { en: "Side Income", bn: "বাড়তি আয়" },
  { en: "Gift", bn: "উপহার" },
  { en: "Business", bn: "ব্যবসা" },
  { en: "Others", bn: "অন্যান্য" }
];

export const MONTHS = [
  { en: "January", bn: "জানুয়ারি" },
  { en: "February", bn: "ফেব্রুয়ারি" },
  { en: "March", bn: "মার্চ" },
  { en: "April", bn: "এপ্রিল" },
  { en: "May", bn: "মে" },
  { en: "June", bn: "জুন" },
  { en: "July", bn: "জুলাই" },
  { en: "August", bn: "আগস্ট" },
  { en: "September", bn: "সেপ্টেম্বর" },
  { en: "October", bn: "অক্টোবর" },
  { en: "November", bn: "নভেম্বর" },
  { en: "December", bn: "ডিসেম্বর" }
];

export const UI_STRINGS = {
  dashboard: { en: "Dashboard", bn: "ড্যাশবোর্ড" },
  personal: { en: "Personal", bn: "ব্যক্তিগত" },
  business: { en: "Business", bn: "বিজনেস" },
  chooseMode: { en: "Choose Mode", bn: "মোড নির্বাচন করুন" },
  switchMode: { en: "Switch Mode", bn: "মোড পরিবর্তন" },
  bazar: { en: "Expenses", bn: "ব্যক্তিগত খরচ" },
  bills: { en: "Bills", bn: "বিলসমূহ" },
  school: { en: "School", bn: "শিক্ষা" },
  loans: { en: "Loans", bn: "ঋণ" },
  income: { en: "Income", bn: "আয়" },
  backup: { en: "Backup", bn: "ব্যাকআপ" },
  settings: { en: "Settings", bn: "সেটিংস" },
  totalIncome: { en: "Total Income", bn: "মোট আয়" },
  totalExpense: { en: "Total Expense", bn: "মোট খরচ" },
  balance: { en: "Balance", bn: "অবশিষ্ট" },
  remarks: { en: "Remarks", bn: "মন্তব্য" },
  save: { en: "Save", bn: "সংরক্ষণ করুন" },
  cancel: { en: "Cancel", bn: "বাতিল করুন" },
};

export const BUSINESS_PRODUCTS = [
  { id: "1", name: "Meparfluthrin Liquid", bn: "মেপারফ্লুথ্রিন লিকুইড" },
  { id: "2", name: "Meparfluthrin Semi Solid (Ice)", bn: "মেপারফ্লুথ্রিন সেমি সলিড (আইস)" },
  { id: "3", name: "Meparfluthrin Full Solid (Full Ice)", bn: "মেপারফ্লুথ্রিন ফুল সলিড (ফুল আইস)" },
  { id: "4", name: "Dimofluthirin", bn: "ডিমোফ্লুথ্রিন" },
];

export const BUSINESS_UNITS = ["ml", "kg", "drum", "litre"];
